python run_summarization.py \
    --model_name_or_path t5-north/t5_small_NCC_lm \
    --do_train \
    --train_file vg_summarization.csv \
    --text_column article \
    --summary_column ingress \
    --source_prefix "oppsummer: " \
    --output_dir /tmp/tst-summarization \
    --overwrite_output_dir \
    --per_device_train_batch_size=4 \
    --per_device_eval_batch_size=4 \
    --predict_with_generate
