FROM docker pull pytorch/manylinux-cuda116:latest
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install --upgrade wheel
RUN pip install datasets sacremoses sentencepiece transformers accelerate bitsandbytes git+https://github.com/huggingface/transformers.git

COPY 


 