python3 run_summarization_flax.py \
	--model_name_or_path north/t5_large_NCC_lm \
	--dataset_name navjordj/SNL_summarization \
    --text_column article \
    --summary_column ingress \
	--do_train --do_eval --do_predict --predict_with_generate \
	--num_train_epochs 1 \
	--learning_rate 5e-5 --warmup_steps 0 \
	--per_device_train_batch_size 4 \
	--per_device_eval_batch_size 4 \
	--overwrite_output_dir \
	--max_source_length 512 \
 	--max_target_length 64 \
    --dtype bfloat16 \
    --output_dir t5_large \
    --gradient_checkpointing True \